
/* File generated by gen_cfile.py. Should not be modified. */

#include "OD_gateway.h"

/**************************************************************************/
/* Declaration of mapped variables                                        */
/**************************************************************************/

/**************************************************************************/
/* Declaration of value range types                                       */
/**************************************************************************/

#define valueRange_EMC 0x9F /* Type for index 0x1003 subindex 0x00 (only set of value 0 is possible) */
UNS32 OD_gateway_valueRangeTest (UNS8 typeValue, void * value)
{
  switch (typeValue) {
    case valueRange_EMC:
      if (*(UNS8*)value != (UNS8)0) return OD_VALUE_RANGE_EXCEEDED;
      break;
  }
  return 0;
}

/**************************************************************************/
/* The node id                                                            */
/**************************************************************************/
/* node_id default value.*/
UNS8 OD_gateway_bDeviceNodeId = 0x00;

/**************************************************************************/
/* Array of message processing information */

const UNS8 OD_gateway_iam_a_slave = 0;

TIMER_HANDLE OD_gateway_heartBeatTimers[3] = {TIMER_NONE,TIMER_NONE,TIMER_NONE};

/*
$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$

                               OBJECT DICTIONARY

$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$$
*/

/* index 0x1000 :   Device Type. */
                    UNS32 OD_gateway_obj1000 = 0x0;	/* 0 */
                    subindex OD_gateway_Index1000[] = 
                     {
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1000, NULL }
                     };

/* index 0x1001 :   Error Register. */
                    UNS8 OD_gateway_obj1001 = 0x0;	/* 0 */
                    subindex OD_gateway_Index1001[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_gateway_obj1001, NULL }
                     };

/* index 0x1003 :   Pre-defined Error Field */
                    UNS8 OD_gateway_highestSubIndex_obj1003 = 0; /* number of subindex - 1*/
                    UNS32 OD_gateway_obj1003[] = 
                    {
                      0x0	/* 0 */
                    };
                    subindex OD_gateway_Index1003[] = 
                     {
                       { RW, valueRange_EMC, sizeof (UNS8), (void*)&OD_gateway_highestSubIndex_obj1003, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1003[0], NULL }
                     };

/* index 0x1005 :   SYNC COB ID */
                    UNS32 OD_gateway_obj1005 = 0x0;   /* 0 */

/* index 0x1006 :   Communication / Cycle Period */
                    UNS32 OD_gateway_obj1006 = 0x0;   /* 0 */

/* index 0x100C :   Guard Time */ 
                    UNS16 OD_gateway_obj100C = 0x0;   /* 0 */

/* index 0x100D :   Life Time Factor */ 
                    UNS8 OD_gateway_obj100D = 0x0;   /* 0 */

/* index 0x1014 :   Emergency COB ID */
                    UNS32 OD_gateway_obj1014 = 0x80 + 0x00;   /* 128 + NodeID */

/* index 0x1016 :   Consumer Heartbeat Time. */
                    UNS8 OD_gateway_highestSubIndex_obj1016 = 3; /* number of subindex - 1*/
                    UNS32 OD_gateway_obj1016[] = 
                    {
                      0x52710,	/* 337680 */
                      0x62710,	/* 403216 */
                      0x12710	/* 75536 */
                    };
                    subindex OD_gateway_Index1016[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_gateway_highestSubIndex_obj1016, NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1016[0], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1016[1], NULL },
                       { RW, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1016[2], NULL }
                     };

/* index 0x1017 :   Producer Heartbeat Time. */
                    UNS16 OD_gateway_obj1017 = 0x0;	/* 0 */
                    subindex OD_gateway_Index1017[] = 
                     {
                       { RW, uint16, sizeof (UNS16), (void*)&OD_gateway_obj1017, NULL }
                     };

/* index 0x1018 :   Identity. */
                    UNS8 OD_gateway_highestSubIndex_obj1018 = 4; /* number of subindex - 1*/
                    UNS32 OD_gateway_obj1018_Vendor_ID = 0x0;	/* 0 */
                    UNS32 OD_gateway_obj1018_Product_Code = 0x0;	/* 0 */
                    UNS32 OD_gateway_obj1018_Revision_Number = 0x0;	/* 0 */
                    UNS32 OD_gateway_obj1018_Serial_Number = 0x0;	/* 0 */
                    subindex OD_gateway_Index1018[] = 
                     {
                       { RO, uint8, sizeof (UNS8), (void*)&OD_gateway_highestSubIndex_obj1018, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1018_Vendor_ID, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1018_Product_Code, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1018_Revision_Number, NULL },
                       { RO, uint32, sizeof (UNS32), (void*)&OD_gateway_obj1018_Serial_Number, NULL }
                     };

/**************************************************************************/
/* Declaration of pointed variables                                       */
/**************************************************************************/

const indextable OD_gateway_objdict[] = 
{
  { (subindex*)OD_gateway_Index1000,sizeof(OD_gateway_Index1000)/sizeof(OD_gateway_Index1000[0]), 0x1000},
  { (subindex*)OD_gateway_Index1001,sizeof(OD_gateway_Index1001)/sizeof(OD_gateway_Index1001[0]), 0x1001},
  { (subindex*)OD_gateway_Index1016,sizeof(OD_gateway_Index1016)/sizeof(OD_gateway_Index1016[0]), 0x1016},
  { (subindex*)OD_gateway_Index1017,sizeof(OD_gateway_Index1017)/sizeof(OD_gateway_Index1017[0]), 0x1017},
  { (subindex*)OD_gateway_Index1018,sizeof(OD_gateway_Index1018)/sizeof(OD_gateway_Index1018[0]), 0x1018},
};

const indextable * OD_gateway_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode)
{
	(void)d;
	int i;
	switch(wIndex){
		case 0x1000: i = 0;break;
		case 0x1001: i = 1;break;
		case 0x1016: i = 2;break;
		case 0x1017: i = 3;break;
		case 0x1018: i = 4;break;
		default:
			*errorCode = OD_NO_SUCH_OBJECT;
			return NULL;
	}
	*errorCode = OD_SUCCESSFUL;
	return &OD_gateway_objdict[i];
}

/* 
 * To count at which received SYNC a PDO must be sent.
 * Even if no pdoTransmit are defined, at least one entry is computed
 * for compilations issues.
 */
s_PDO_status OD_gateway_PDO_status[1] = {s_PDO_status_Initializer};

const quick_index OD_gateway_firstIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const quick_index OD_gateway_lastIndex = {
  0, /* SDO_SVR */
  0, /* SDO_CLT */
  0, /* PDO_RCV */
  0, /* PDO_RCV_MAP */
  0, /* PDO_TRS */
  0 /* PDO_TRS_MAP */
};

const UNS16 OD_gateway_ObjdictSize = sizeof(OD_gateway_objdict)/sizeof(OD_gateway_objdict[0]); 

CO_Data OD_gateway_Data = CANOPEN_NODE_DATA_INITIALIZER(OD_gateway);

