
/* File generated by gen_cfile.py. Should not be modified. */

#ifndef OD_GATEWAY_H
#define OD_GATEWAY_H

#include "data.h"

/* Prototypes of function provided by object dictionnary */
UNS32 OD_gateway_valueRangeTest (UNS8 typeValue, void * value);
const indextable * OD_gateway_scanIndexOD (CO_Data *d, UNS16 wIndex, UNS32 * errorCode);

/* Master node data struct */
extern CO_Data OD_gateway_Data;

#endif // OD_GATEWAY_H
